version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"  # Map container port 80 (default) to host port 80
    volumes:
      - ./nginx.conf:/level_up_academy/level_up_academy/nginx/nginx.conf

  web:
    container_name: "backend"
    build: 
      context: .
      dockerfile: level-up-academy/Dockerfile
    restart: always
    ports:
      - 8001:8001
    env_file:
      - "level-up-academy/level_up_academy/.env"
    depends_on:
      - db
    network_mode: "services:my-network"

  bot:
    container_name: "tgbot"
    build: 
      context: .
      dockerfile: tgbot-my-edu/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - "tgbot-my-edu/.env"
    depends_on:
      - db
    network_mode: "services:my-network"

  db:
    container_name: pg_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=level_up_academy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2001
      - POSTGRES_HOST=localhost
      

networks:
  my-network: