db:
	sudo -u postgres psql level_up_academy_db

migs:
	python3 manage.py makemigrations

mig:
	python3 manage.py migrate

run:
	python3 manage.py runserver 8001

super:
	python3 manage.py createsuperuser
